clear all;
opengl software
GUI.main =figure('position',[15  10 1000  500],...
            'color',[0.925 0.913 0.687],...
        'name',' [GUI]: Detction and Sorting Of HFOs');
GUI_welcome=uicontrol(gcf,'style','text', 'position',[10 450 80 30],...
'string', 'Load Data');
GUI_database = uicontrol('Style','pushbutton','String','Browse','Position', [100 450 80 30],...
'Callback','[F,P] = uigetfile(''*.mat'',''select the M-file''),eee');
CC=0;
coupos=0;

